"""
coevokg.prompts — Centralized prompt template library.

All role-specific prompt strings (Proposer, Solver, Judge, Quality Checker)
are defined here and imported by their respective modules.
"""

from coevokg.prompts.proposer_prompts import (
    WALK_SYSTEM_PROMPT_EN,
    WALK_USER_PROMPT_EN,
    WALK_SYSTEM_PROMPT_ZH,
    WALK_USER_PROMPT_ZH,
    HOTPOT_SYSTEM_PROMPT_EN,
    HOTPOT_USER_PROMPT_EN,
    HOTPOT_USER_PROMPT_EN_NO_CHAIN,
    HOTPOT_SYSTEM_PROMPT_ZH,
    HOTPOT_USER_PROMPT_ZH,
    HOTPOT_USER_PROMPT_ZH_NO_CHAIN,
    # backward compat aliases
    _WALK_SYSTEM_PROMPT_EN,
    _WALK_USER_PROMPT_EN,
    _WALK_SYSTEM_PROMPT_ZH,
    _WALK_USER_PROMPT_ZH,
    _WALK_SYSTEM_PROMPT,
    _HOTPOT_SYSTEM_PROMPT_EN,
    _HOTPOT_USER_PROMPT_EN,
    _HOTPOT_USER_PROMPT_EN_NO_CHAIN,
    _HOTPOT_SYSTEM_PROMPT_ZH,
    _HOTPOT_USER_PROMPT_ZH,
    _HOTPOT_USER_PROMPT_ZH_NO_CHAIN,
)

from coevokg.prompts.solver_prompts import (
    SOLVER_SYSTEM_PROMPT,
    SOLVER_USER_PROMPT,
    RSEARCH_SOLVER_SYSTEM_PROMPT,
    RSEARCH_SOLVER_USER_PROMPT,
)

from coevokg.prompts.judge_prompts import (
    JUDGE_SYSTEM_PROMPT,
    JUDGE_EVALUATION_PROMPT,
    JUDGE_ANSWER_FROM_MATERIALS_PROMPT,
)

from coevokg.prompts.quality_check_prompts import (
    QUALITY_CHECK_SYSTEM_PROMPT,
    QUALITY_CHECK_USER_PROMPT,
    RULE_GENERATION_SYSTEM_PROMPT,
    RULE_GENERATION_USER_PROMPT,
)

__all__ = [
    # Proposer
    "WALK_SYSTEM_PROMPT_EN", "WALK_USER_PROMPT_EN",
    "WALK_SYSTEM_PROMPT_ZH", "WALK_USER_PROMPT_ZH",
    "HOTPOT_SYSTEM_PROMPT_EN", "HOTPOT_USER_PROMPT_EN", "HOTPOT_USER_PROMPT_EN_NO_CHAIN",
    "HOTPOT_SYSTEM_PROMPT_ZH", "HOTPOT_USER_PROMPT_ZH", "HOTPOT_USER_PROMPT_ZH_NO_CHAIN",
    # Backward compat
    "_WALK_SYSTEM_PROMPT_EN", "_WALK_USER_PROMPT_EN",
    "_WALK_SYSTEM_PROMPT_ZH", "_WALK_USER_PROMPT_ZH", "_WALK_SYSTEM_PROMPT",
    "_HOTPOT_SYSTEM_PROMPT_EN", "_HOTPOT_USER_PROMPT_EN", "_HOTPOT_USER_PROMPT_EN_NO_CHAIN",
    "_HOTPOT_SYSTEM_PROMPT_ZH", "_HOTPOT_USER_PROMPT_ZH", "_HOTPOT_USER_PROMPT_ZH_NO_CHAIN",
    # Solver
    "SOLVER_SYSTEM_PROMPT", "SOLVER_USER_PROMPT",
    "RSEARCH_SOLVER_SYSTEM_PROMPT", "RSEARCH_SOLVER_USER_PROMPT",
    # Judge
    "JUDGE_SYSTEM_PROMPT", "JUDGE_EVALUATION_PROMPT", "JUDGE_ANSWER_FROM_MATERIALS_PROMPT",
    # Quality check
    "QUALITY_CHECK_SYSTEM_PROMPT", "QUALITY_CHECK_USER_PROMPT",
    "RULE_GENERATION_SYSTEM_PROMPT", "RULE_GENERATION_USER_PROMPT",
]
